/*#
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
 */

package Euler2;

/**
 *
 * @author Richard Bowen
 */
public class Main {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Timer newTimer = new Timer();
        // Variable sum will be used to store the sum of the numbers
        int sum = 2;
        //Variables to hold two consecutive numbers
        int fib1 = 0;
        int fib2 = 2;
        //Iterate fibonacci from 1 to 3999999 
        //and if divisible by two, add it to sum
        for(int i = 3;i<4000000;i++)
        {
            //Change fib1 to the value of i
            fib1 = i;      
            if(i%2==0)
            {
                //add the value of i to the current value of sum
                sum+=i;
            }
            //Make i equal to the sum of the two current numbers 
            //Subtract 1 for the iterator
            i = fib1 + fib2 - 1;
            //Make the second variable equal to the first            
            fib2 = fib1;
           
        }
        System.out.println(sum);
        newTimer.end();
    }
    
}
